name: flutter_final_revhub
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  audioplayers: ^6.6.0
  cupertino_icons: ^1.0.8
  supabase_flutter: ^2.12.4 
  supabase_auth_ui: ^0.5.5
  google_sign_in: ^6.2.1
  sign_in_button: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4
  change_app_package_name: ^1.5.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"

flutter:
  uses-material-design: true
  fonts:  
    - family: AppFont
      fonts:
        - asset: assets/fonts/NotoSansTC-Regular.ttf
        - asset: assets/fonts/NotoSansTC-Bold.ttf
  assets:
    - assets/background/
    - assets/brands/Benz/AMG_GTR/images/cover/
    - assets/brands/Benz/AMG_GTR/images/detail/
    - assets/brands/Benz/AMG_GTR/sound/
    - assets/brands/BMW/M3_Touring/images/cover/
    - assets/brands/BMW/M3_Touring/images/detail/
    - assets/brands/BMW/M3_Touring/sound/
    - assets/brands/Nissan/Z300/images/cover/
    - assets/brands/Nissan/Z300/images/detail/
    - assets/brands/Nissan/Z300/sound/
    - assets/brands/BMW/M4/images/cover/
    - assets/brands/BMW/M4/images/detail/
    - assets/brands/BMW/M4/sound/
    - assets/brands/Porsche/911 GT3 RS/images/cover/
    - assets/brands/Porsche/911 GT3 RS/images/detail/
    - assets/brands/Porsche/911 GT3 RS/sound/
    - assets/brands/Porsche/Cayman GT4 RS/images/cover/
    - assets/brands/Porsche/Cayman GT4 RS/images/detail/
    - assets/brands/Porsche/Cayman GT4 RS/sound/
    - assets/brands/Audi/RS6 Avant/images/cover/
    - assets/brands/Audi/RS6 Avant/images/detail/
    - assets/brands/Audi/RS6 Avant/sound/
    - assets/brands/Nissan/R34/images/cover/
    - assets/brands/Nissan/R34/images/detail/
    - assets/brands/Nissan/R34/sound/
    - assets/brands/Toyota/GR Yaris/images/cover/
    - assets/brands/Toyota/GR Yaris/images/detail/
    - assets/brands/Toyota/GR Yaris/sound/
    - assets/brands/Toyota/GR GT/images/cover/
    - assets/brands/Toyota/GR GT/images/detail/
    - assets/brands/Toyota/GR GT/sound/
    - assets/brands/Ford/Mustang/images/cover/
    - assets/brands/Ford/Mustang/images/detail/
    - assets/brands/Ford/Mustang/sound/
    - assets/brands/Mazda/Miata NA/images/cover/
    - assets/brands/Mazda/Miata NA/images/detail/
    - assets/brands/Mazda/Miata NA/sound/
    - assets/bgms/Moavii - Adventure (freetouse.com).mp3
    